# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/k7325_676/2_mig/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ms_fifo/ms_fifo.xci
# IP: The module: 'ms_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/k7325_676/2_mig/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ms_fifo/ms_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ms_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/k7325_676/2_mig/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ms_fifo/ms_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ms_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/k7325_676/2_mig/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ms_fifo/ms_fifo.xci
# IP: The module: 'ms_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/k7325_676/2_mig/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ms_fifo/ms_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ms_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/k7325_676/2_mig/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ms_fifo/ms_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ms_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
