# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_1.xci
# IP: The module: 'ila_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_1.xci
# IP: The module: 'ila_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
