# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/RGB_MEM/RGB_MEM.xci
# IP: The module: 'RGB_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/RGB_MEM/RGB_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RGB_MEM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/RGB_MEM/RGB_MEM.xci
# IP: The module: 'RGB_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/ggd/MK7160FA/03_demo/02_example_mig_ddr_k7/03_img_camera/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/RGB_MEM/RGB_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RGB_MEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
