# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/FIFO_1bit/FIFO_1bit.xci
# IP: The module: 'FIFO_1bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/FIFO_1bit/FIFO_1bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/FIFO_1bit/FIFO_1bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/FIFO_1bit/FIFO_1bit.xci
# IP: The module: 'FIFO_1bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/FIFO_1bit/FIFO_1bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/FIFO_1bit/FIFO_1bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
