# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/cordic_square_root/cordic_square_root.xci
# IP: The module: 'cordic_square_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/cordic_square_root/cordic_square_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_square_root'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/cordic_square_root/cordic_square_root.xci
# IP: The module: 'cordic_square_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GGD_work/program/match/img_camera_ov5640_720p/mig_ddr.srcs/sources_1/ip/cordic_square_root/cordic_square_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_square_root'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
